public/.maintenance.php

Retry-After header is unreliable, bad browser support

maintenance: reload browser on server ready

---

mango.json
theme/utils/mango-cli-integration.php
theme/views/@layout.latte

- https://github.com/manGoweb/mango-cli/blob/master/docs/config.md#buildstamp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangoweb/mangopress/55)

Buildstamp: mango-cli integration

---

composer.json
composer.lock

bcrypt passwords plugin

---

README.md
composer.json
composer.lock
config/config.neon
theme/admin/builder.latte
theme/admin/builder.php
theme/admin/builderResult.latte

> deploy of a static pages to AWS S3! 😱 
Requires: https://github.com/manGoweb/builder running instance
And the docs: https://github.com/manGoweb/MangoPress/wiki/Builder
Sample project: https://github.com/manGoweb/rekola-cms
Original draft: https://github.com/manGoweb/mangoweb-cz-wp-cms

Adding Builder core files

---

public/wp-content/mu-plugins/wp-admin-add-slash.php

redirect wp-admin => wp-admin/

---

public/wp-content/mu-plugins/register-theme-directory.php

fix error output on installation page

---

wp-cli.yml

Because I'm a lazy dog and don't want to install plugins etc by hand.
http://wp-cli.org/

Added config file for the WP-CLI tool

---

mango.yaml
theme/scripts/components/ExampleAdminPage.jsx
theme/scripts/components/ExampleMetabox.jsx
theme/scripts/components/PageRolesMetabox.es6
theme/scripts/components/PageRolesMetabox.jsx
theme/scripts/wp-admin.es6

Fix react component
Fix burbon version

Mangopress next fixes

---

app/sentry.php
public/wp-config.php

Fix missing/excess brackets

---

theme/views/@layout.latte
theme/views/styleguide/index.latte

I've replaced absolute path `/assets` with `$assetsPath` variable so the template works even if you run it in nested folder

Fix assets path

---

mango.yaml
package-lock.json
package.json

Move deps to package.json

---

config/utils/redirect-to-missing-slash.php

- this was merged to next, after next was already on master. So lets merge it back to master :)

Next to master

---

config/utils/register-metaboxes.php

This file was just missing, nothing special.

Add forgotten register-metaboxes

---

config/utils/lib/neon-schema.php

Fix group edit of posts

---

config/utils/lib/neon-schema.php

Supported custom eval on any key in neon-config with @ prefix

---

config/utils/templating.php

Closes https://github.com/manGoweb/MangoPress/issues/161

global $Post in templates

---

config/config.local.sample.neon
config/utils/dangerouslyDisablePasswords.php

🤡 when you need to switch users really fast or dont know their passwords. Only for dev environment!
```
parameters:
dangerouslyDisablePasswords: on
```

Dangerously disable passwords

---

config/utils/lib/neon-schema.php
theme/utils/payloadHelpers.php

Autogenerating payloads

---

composer.json
composer.lock

requiring nette packages without `nette/deprecated` (so it shall work in PHP 7.2)

explicitly required nette

---

config/utils/register-image-sizes.php

Images: allow size with height auto

---

mango.yaml
theme/front-page.php
theme/styles/_variables.sass
theme/styles/index.sass
theme/styles/styleguide.sass
theme/utils/components.php
theme/utils/varExport.php
theme/views/components/example.latte
theme/views/components/example.neon
theme/views/components/example.sass
theme/views/styleguide.latte

directory `views/components` is now magical, and automatically generates styleguide from these Latte components. You can declare visible variants of components by using neon file with same name. Also recomended to use sass file with same name.

add basic styleguide

---

bin/init-project.sh
bin/update.sh

Use mu-plugins from private gitlab

update mu-plugins target

---

config/bootstrap.php

Useful on MacOS: https://tracy.nette.org/en/open-files-in-ide#toc-mac-os-x
For VSCode, you can add to your profile:
```sh
export TRACY_EDITOR_URL=vscode://file/%file:%line
```

Add configurable Tracy editor

---

theme/emails/@htmlButton.latte
theme/emails/@layout.latte
theme/emails/hello.latte
theme/emails/styles.php
theme/utils/emails.php

Email helpers

---

config/utils/forms.php

Make $Post available in forms controllers

---

config/utils/mango-cli-integration.php

Change in upcoming mango-cli version (++v3.0.1)

mango-cli-integration: snippet moved to dist_dir

---

composer.lock
config/utils/forms.php
config/utils/page-roles.php
package-lock.json
package.json
theme/forms/contact.php

Old form handler didn't distinguish `not submitted` and `not valid` states.

Better form handler
